version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8765:8765"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      mynetwork:
        ipv4_address: 172.16.230.2

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 172.16.230.3
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  cache:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      mynetwork:
        ipv4_address: 172.16.230.4
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.16.230.0/24

volumes:
  mysql_data:
  redis_data:
